E2E test template
aerogear/aerogear-sdk-e2e-tests pull request #1
Opened 2018-03-07 00:09 UTC by wojta

2018-03-07 16:39 UTC, wei-lee reviewed
LGTM

2018-03-08 14:06 UTC, twnolan requested changes
Other than the comments I have made this code looks good to me. 

However the test has failed due to missing file which is in mentioned in .gitignore:

`/home/thnolan/feedhenry/aerogear-sdk-e2e-tests/local.properties`

Details of how to create this file and example file need to be placed in README.md

2018-03-08 14:06 UTC, twnolan commented on sdk-e2e/src/test/kotlin/org/aerogear/sdk_e2e_tests/pageobjects/unimportant/ChromeIntroScreen.kt
> +interface ChromeIntroScreen : PageObject {
It is possible to set the chromeOptions when starting a test and disable things such as the welcome page, setting chrome as default pop up, cert errors etc. This would be much more preferable than trying to create our own classes to control the logic required to handle all of the possible problems.

https://github.com/twnolan/appium-experimentation/blob/master/test/login-logout.spec.js#L20 - this is how to disable some of these in javascript

https://appium.io/docs/en/writing-running-appium/caps/ - this has all the information on desired capabilities for appium, and some information on android and ios only capabilities regarding chrome and safari options

2018-03-08 14:06 UTC, twnolan commented on README.md
> +
There should also be a section on an example of creating a test, or link to the library documentation for making a test as this is a non-standard library.

2018-03-08 14:18 UTC, wojta commented on sdk-e2e/src/test/kotlin/org/aerogear/sdk_e2e_tests/pageobjects/unimportant/ChromeIntroScreen.kt
> +interface ChromeIntroScreen : PageObject {
thanks, I wasn't aware of that.

2018-03-08 14:18 UTC, wojta commented on README.md
> +
yes, that's right. It should be.

2018-03-12 14:42 UTC, wojta commented
finalized changes @twnolan, please approve if it's ok

2018-03-12 14:42 UTC, wojta commented
sorry, forgot that local.properties

2018-03-13 10:35 UTC, twnolan approved these changes
LGTM now.

2018-03-13 10:46 UTC, merged